version: '3'
services:
  web:
    image: sunsc-web
    build: .
    volumes:
      - ./rssbro/:/var/rssbro
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    env_file: .env

  rabbitmq:
    image: rabbitmq:3.7-management
    env_file: .env
    ports:
      - 15672:15672

  worker:
    build: .
    command: celery -A rssbro worker --loglevel INFO
    volumes:
      - ./rssbro/:/var/rssbro
    env_file: .env
    depends_on:
      - rabbitmq
      - db


  beat:
    build: .
    command: celery -A rssbro beat --loglevel INFO --pidfile=
    volumes:
      - ./rssbro/:/var/rssbro
    env_file: .env
    depends_on:
      - rabbitmq
      - db
